<?php
/**
 * @file
 * Information a
 */
/**
 * Implements hook_webform_component_info().
 */
function webform_textarea_html5_webform_component_info() {
  $components = array();
  $components['textarea_html5'] = array(
    'label'       => t('Text zone HTML5'),
    'description' => t('Text zone HTML5.'),
    'features'    => array(
      // Add content to CSV downloads. Defaults to TRUE.
      'csv'           => TRUE,
      // Show this component in e-mailed submissions. Defaults to TRUE.
      'email'         => TRUE,
      // Allow this component to be used as an e-mail FROM or TO address.
      // Defaults to FALSE.
      'email_address' => FALSE,
      // Allow this component to be used as an e-mail SUBJECT or FROM name.
      // Defaults to FALSE.
      'email_name'    => FALSE,
      // This component may be toggled as required or not. Defaults to TRUE.
      'required'      => TRUE,
      // This component has a title that can be toggled as displayed or not.
      'title_display' => TRUE,
      // This component has a title that can be displayed inline.
      'title_inline'  => TRUE,
      // If this component can be used as a conditional SOURCE. All components
      // may always be displayed conditionally, regardless of this setting.
      // Defaults to TRUE.
      'conditional'   => TRUE,
      // If this component allows other components to be grouped within it
      // (like a fieldset or tabs). Defaults to FALSE.
      'group'         => FALSE,
      // If this component can be used for SPAM analysis, usually with Mollom.
      'spam_analysis' => FALSE,
      // If this component saves a file that can be used as an e-mail
      // attachment. Defaults to FALSE.
      'attachment'    => FALSE,
    ),
    'file'        => 'webform_textarea_html5.components.inc',
  );
  return $components;
}
/**
 * Implements hook_theme_registry_alter().
 */
 

//hook pour ajouter le maxlengt aux textareas
function webform_textarea_html5_theme_registry_alter(&$theme_registry) {
  // Override the default field-collection-item.tpl.php with our own.

  if (isset($theme_registry['textarea'])) {
    $module_path = drupal_get_path('module', 'webform_textarea_html5');
    $theme_registry['textarea']['theme path'] = $module_path;
    $theme_registry['textarea']['template'] = $module_path . '/templates/textarea_html5';
  }

}

